# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint for twitch presence

Globals:
    Function:
        Environment:
            Variables:
                SQS_URL: !Ref SaveTwitchPresenceQueue

Resources:
    SaveTwitchPresenceQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: deferred-save-twitch-presence
            VisibilityTimeout: 601
    StartSaveTwitchPresenceFunction2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: start-save-twitch-presence.default
            Runtime: nodejs18.x
            CodeUri: ./dist/start-save-twitch-presence
            Timeout: 5
            # Layers:
            #     - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - SecretsManagerReadWrite
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-start-save-twitch-presence-2
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE
    ProcessSaveTwitchPresenceFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: process-save-twitch-presence.default
            Runtime: nodejs18.x
            CodeUri: ./dist/process-save-twitch-presence
            MemorySize: 128
            ReservedConcurrentExecutions: 5
            # Layers:
            #     - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: process-save-twitch-presence
            Timeout: 60
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt SaveTwitchPresenceQueue.Arn
                        # BatchSize: 1
    RetrieveTwitchPresenceFunction2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: retrieve-twitch-presence.default
            Runtime: nodejs18.x
            CodeUri: ./dist/retrieve-twitch-presence
            Timeout: 29
            # Layers:
            #     - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - SecretsManagerReadWrite
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-retrieve-twitch-presence-2
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE